Repository education/GitHubGraduation-2022, pull requests merged in 2022-06, with the labels that each got.

#1830 Create shubhi2000.md
  _data/shubhi2000/shubhi2000.md
Labels: ✅ Ready for merge

#5883 Github Graduation Year 2022
  _data/opensourcebangladesh/opensourcebangladesh.md
Labels: ✅ Ready for merge

#7591 Create ongzzzzzz.md
  _data/ongzzzzzz/ongzzzzzz.md
Labels: ✅ Ready for merge

#8106 Create khalilhajrii.md
  _data/khalilhajrii/khalilhajrii.md
Labels: ✅ Ready for merge

#8107 Create Jimmy5467.md
  _data/Jimmy5467/Jimmy5467.md
Labels: ✅ Ready for merge

#8108 create prathameshThakur.md
  _data/prathameshThakur/prathameshThakur.md
Labels: ✅ Ready for merge

#8117 Created shalatan.md
  _data/shalatan/shalatan.md
Labels: ✅ Ready for merge

#8119 Create devashish-7.md
  _data/devashish-7/devashish-7.md
Labels: ✅ Ready for merge

#8124 Create Chaitalykundu.md
  _data/Chaitalykundu/Chaitalykundu.md
Labels: ✅ Ready for merge

#8164 Create Usha103.md
  _data/Usha103/Usha103.md
Labels: ✅ Ready for merge

#7205 Add folder and file
  _data/htetpyaeaung/htetpyaeaung.md
Labels: ✅ Ready for merge

#8109 Update JustFossa.md
  _data/JustFossa/JustFossa.md
Labels: ✅ Ready for merge

#8111 Create Prashim-hack.md
  _data/Prashim-hack/Prashim-hack.md
Labels: ✅ Ready for merge

#8112 Create wanisramdani.md
  _data/wanisramdani/wanisramdani.md
Labels: ✅ Ready for merge

#8114 Create AyushKoul00.md
  _data/AyushKoul00/AyushKoul00.md
Labels: ✅ Ready for merge

#8122 Create abhishekapk.md
  _data/abhishekapk/abhishekapk.md
Labels: ✅ Ready for merge

#8130 Create mohanishdc7.md
  _data/mohanishdc7/mohanishdc7.md
Labels: ✅ Ready for merge

#8137 added Omraj Sharma
  _data/omrajsharma/omrajsharma.md
Labels: ✅ Ready for merge

#8163 Add lifesaver0129 info to main
  _data/lifesaver0129/lifesaver0129.md
Labels: ✅ Ready for merge

#8161 Create mijoo308.md
  _data/mijoo308/mijoo308.md
Labels: ✅ Ready for merge

#8160 ra1n pull
  _data/ra1nst0rm3d/ra1nst0rm3d.md
Labels: ✅ Ready for merge

#8159 Create qwerty22121998.md
  _data/qwerty22121998/qwerty22121998.md
Labels: ✅ Ready for merge

#8157 Create berkekbgz.md
  _data/berkekbgz/berkekbgz.md
Labels: ✅ Ready for merge

#8134 Create golu-99.md
  _data/golu-99/golu-99.md
Labels: ✅ Ready for merge

#8135 Add files via upload
  _data/abhinavsp0730/abhinavsp0730.md
Labels: ✅ Ready for merge

#8133 add Vishal-raj-1
  _data/Vishal-raj-1/Vishal-raj-1.md
Labels: ✅ Ready for merge

#8138 Khushik514 added
  _data/Khushik514/Khushik514.md
Labels: ✅ Ready for merge

#8142 Create AlexDev404.md
  _data/AlexDev404/AlexDev404.md
Labels: ✅ Ready for merge

#8143 updated changes
  _data/pratham-10/pratham-10.md
Labels: ✅ Ready for merge

#8144 docs: added re-Tick profile data
  _data/re-Tick/re-Tick.md
Labels: ✅ Ready for merge

#8145 Create AMr4X.md
  _data/AMr4X/AMr4X.md
Labels: ✅ Ready for merge

#8146 wow
  _data/colinhartigan/colinhartigan.md
Labels: ✅ Ready for merge

#8147 Create Bikramjit21.md
  _data/Bikramjit21/Bikramjit21.md
Labels: ✅ Ready for merge

#8149 Create vikkastiwari.md
  _data/vikkastiwari/vikkastiwari.md
Labels: ✅ Ready for merge

#8150 added my profile
  _data/Bimalesh-Seth/Bimalesh-Seth.md
Labels: ✅ Ready for merge

#8153 Create arslanafzalch.md
  _data/arslanafzalch/arslanafzalch.md
Labels: ✅ Ready for merge

#8154 Create Bhavya-Tripathi.md
  _data/Bhavya-Tripathi/Bhavya-Tripathi.md
Labels: ✅ Ready for merge

#8156 HighYoda signing off!!
  _data/grtcoder/grtcoder.md
Labels: ✅ Ready for merge

#8126 Create jaehoo1.md
  _data/jaehoo1/jaehoo1.md
Labels: ✅ Ready for merge

#8062 New PR
  _data/gkrockz/gkrockz.md
Labels: ✅ Ready for merge

#6194 Create gangapurambhargav.md
  _data/gangapurambhargav/gangapurambhargav.md
Labels: 🎉 Previously Graduated

#6052 Add Callum OKane
  _data/callumok2004/callumok2004.md
Labels: 🎉 Previously Graduated

#2212 Submission
  _data/jayprakash07/jayprakash07.md
Labels: ✅ Ready for merge

#2794 trying again because of previously graduated issue
  _data/ankushKun/ankushKun.md
Labels: ✅ Ready for merge

#4283 Create qwertyreboot.md
  _data/qwertyreboot/qwertyreboot.md
Labels: ✅ Ready for merge

#4312 Create abhinandanarya06.md
  _data/abhinandanarya06/abhinandanarya06.md
Labels: ✅ Ready for merge

#4344 Create StarTrooper.md
  _data/StarTrooper08/StarTrooper.md
Labels: ✅ Ready for merge

#4486 added Sanan4li
  _data/Sanan4li/Sanan4li.md
Labels: ✅ Ready for merge, 🎉 Previously Graduated

#4607 Create moli-debugger.md
  _data/moli-debugger/moli-debugger.md
Labels: ✅ Ready for merge

#4651 Added my file.
  _data/preetvadaliya/preetvadaliya.md
Labels: ✅ Ready for merge

#4935 Create Naveenkumar0405.md
  _data/Naveenkumar0405/Naveenkumar0405.md
Labels: ✅ Ready for merge

#4947 Create SupaliOjha.md
  _data/SupaliOjha/SupaliOjha.md
Labels: ✅ Ready for merge

#5113 Adding EmmaCodes254 md file
  _data/EmmahCodes254/EmmahCodes254.md
Labels: ✅ Ready for merge

#5939 Create daminebenq.md
  _data/daminebenq/daminebenq.md
Labels: ✅ Ready for merge

#5992 Add samuelramox
  _data/samuelramox/samuelramox.md
Labels: ✅ Ready for merge

#6178 Added paovazq to the yearbook!
  _data/paovazq/paovazq.md
Labels: ✅ Ready for merge

#6713 Join GithubGraduation 2022.
  _data/okcd00/okcd00.md
Labels: ✅ Ready for merge

#6779 Create nikhiltripathi1.md
  _data/nikhiltripathi1/nikhiltripathi1.md
Labels: ✅ Ready for merge

#6964 added harshithkumar2.md
  _data/harshithkumar2/harshithkumar2.md
Labels: ✅ Ready for merge

#7134 Create LakinduK.md
  _data/LakinduK/LakinduK.md
Labels: ✅ Ready for merge

#7370 Create Utsav4852.md
  _data/Utsav4852/Utsav4852.md
Labels: ✅ Ready for merge

#7668 Created my data folder
  _data/arnoob16/arnoob16.md
Labels: ✅ Ready for merge

#7857 Graduation Profile.
  _data/dev-rb/dev-rb.md
Labels: ✅ Ready for merge

#4106 Create PradyumnaKrishna.md
  _data/PradyumnaKrishna/PradyumnaKrishna.md
Labels: ✅ Ready for merge

#5361 Create supersharmapunit.md
  _data/supersharmapunit/supersharmapunit.md
Labels: ✅ Ready for merge
